from __future__ import annotations
import pathlib

BASE_DIR: pathlib.Path = pathlib.Path(__file__).parent.resolve()
PROMPTS_DIR: pathlib.Path = BASE_DIR / "prompts"
SCHEMAS_DIR: pathlib.Path = BASE_DIR / "schemas"
COMMS_DIR: pathlib.Path = BASE_DIR / "comms"
INBOX_PATH: pathlib.Path = COMMS_DIR / "inbox.json"
SCREEN_LOCK_PATH: pathlib.Path = COMMS_DIR / "screen_lock.json"

LMS_HOSTS: list[str] = ["http://localhost:1234"]
ACP_TIMEOUT: float = 90.0
LMS_TIMEOUT: int = 120

BUDGET_PLANNER_IN: int = 8000
BUDGET_PLANNER_OUT: int = 4000
BUDGET_ACTOR_IN: int = 8000
BUDGET_ACTOR_OUT: int = 4000
BUDGET_VERIFIER_IN: int = 8000
BUDGET_VERIFIER_OUT: int = 4000
BUDGET_REFLECTOR_IN: int = 16000
BUDGET_REFLECTOR_OUT: int = 8000

DELAY_STARTUP: float = 5.0
DELAY_BETWEEN_ITERATIONS: float = 3.0

DELAY_FOCUS: float = 0.5
DELAY_CURSOR_SETTLE: float = 0.05
DELAY_MOUSE_HOLD: float = 0.05
DELAY_KEY_INTER: float = 0.03
DELAY_CHAR_SEND: float = 0.03
MAX_WAIT_SECONDS: float = 10.0

TREE_WALK_TIMEOUT: float = 5.0
PROBE_STEP_PX: int = 70

MAX_HISTORY_ENTRIES: int = 200
MAX_SIGNATURES: int = 100
MAX_LESSONS: int = 50
MAX_LEDGER_ENTRIES: int = 200
CONTEXT_HISTORY_LIMIT: int = 10

STAGNATION_HALT_THRESHOLD: float = 0.95
STAGNATION_HALT_SUSTAINED: int = 5

PIPELINE_LORENZ: bool = True
PIPELINE_PID: bool = True
PIPELINE_JACOBIAN: bool = True

LORENZ_SIGMA: float = 10.0
LORENZ_RHO: float = 28.0
LORENZ_BETA: float = 8.0 / 3.0
LORENZ_DT: float = 0.02
LORENZ_MAG_CAP: float = 80.0
LORENZ_RHO_SENSITIVITY: float = 1.5
LORENZ_BETA_SENSITIVITY: float = 0.3

PID_KP: float = 1.0
PID_KI: float = 0.3
PID_KD: float = 0.8
PID_INTEGRAL_MAX: float = 5.0
PID_DEAD_ZONE: float = 0.05

STAGNATION_WEIGHT_FAILURES: float = 5.0
STAGNATION_WEIGHT_MISS: float = 4.0
STAGNATION_WEIGHT_REPETITION: float = 12.0
STAGNATION_WEIGHT_SCREEN: float = 6.0
STAGNATION_NORMALIZER: float = 28.0

REFLECT_THRESHOLD: float = 0.3
DISTILL_THRESHOLD: float = 2.0

LLM_TEMPERATURE: float = 0.22
LLM_TOP_P: float = 0.92
LLM_MAX_TOKENS: int = 200000
